name: Build and Upload Xenomorph Project Assets

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4.1.1
        with:
          # Cache target directory to skip re-building if cache exists
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
          upload-chunk-size: 20000000  # Optional: 20MB chunk size to upload cache
          enableCrossOsArchive: true  # Optional: Cross-platform caching enabled

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (including protobuf-compiler)
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Verify protoc installation
        run: protoc --version

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Build for Linux
        run: cargo build --release --bin xenom-wallet --bin xenom

      - name: Upload release artifacts (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: release-binaries-linux
          path: |
            target/release/xenom-wallet
            target/release/xenom

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Protobuf Compiler
        run: brew install protobuf

      - name: Verify protoc installation
        run: protoc --version

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Build for macOS
        run: cargo build --release --bin xenom-wallet --bin xenom

      - name: Upload release artifacts (macOS)
        uses: actions/upload-artifact@v3
        with:
          name: release-binaries-macos
          path: |
            target/release/xenom-wallet
            target/release/xenom

  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux build artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-binaries-linux

      - name: Download macOS build artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-binaries-macos

      - name: List files in the workspace
        run: ls -la  # This will help you verify that the artifacts are downloaded

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            linux/xenom-wallet
            linux/xenom
            macos/xenom-wallet
            macos/xenom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure you are using the token

      - name: Notify success
        run: echo "Release created successfully!"
